# docker-compose.yml
version: '3.8'

services:
  fastping:
    build: .
    ports:
      - "9876:9876"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - DATABASE_URL=sqlite:///data/fastping.db
      - SECRET_KEY=${SECRET_KEY:-dev-secret-change-in-production}
      - PAYPAL_CLIENT_ID=${PAYPAL_CLIENT_ID}
      - PAYPAL_CLIENT_SECRET=${PAYPAL_CLIENT_SECRET}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9876/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - fastping-network

  # Optional Redis for ultra-fast caching
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes
    networks:
      - fastping-network

  # Optional Nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - fastping
    restart: unless-stopped
    networks:
      - fastping-network

networks:
  fastping-network:
    driver: bridge

volumes:
  redis-data: